baseURL = 'https://mahlstrom.dev/'
languageCode = 'en-us'
paginate = 7 # Equals the number of chapters in Kundera's novels.
pluralizelisttitles = false

[params]
    brand = "mahlstrom.dev"
    brand_image = "/images/mahlstrom-profile-new.jpeg"
    description = "Hey, I'm Martin. Web developer, Arch user, cybersecurity enthusiast. This is my blog."
    dark_mode = true
    favicon = "/icons/icon-open-source.png"

    front_page_content = ["posts"]

    menu = [
        {Name = "About Me", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 3},
        {Name = "Projects", URL = "/projects/", HasChildren = false},
        {Name = "Links", URL = "/links/", HasChildren = false},
    ]

    github_url = "https://github.com/m-ahlstrom"
    gitlab_url = "https://gitlab.com/m-ahlstrom"
    linkedin_url = "https://www.linkedin.com/in/m-ahlstrom/"
    mastodon_url = "https://mastodon.social/@mahlstrom"
    telegram_url = "https://t.me/mahlstrom_dev"
    rss_icon = true
    rss_section = "posts"

    # Hex colors for sidebar.
    moon_sun_background_color = "#515151"
    moon_sun_color = "#FFF"
    sidebar_a_color = "#FFF"
    sidebar_bg_color = "#202020"
    sidebar_h1_color = "#FFF"
    sidebar_img_border_color = "#515151"
    sidebar_p_color = "#909090"
    sidebar_socials_color = "#FFF"

    # Hex colors for content in light mode.
    code_color = "#000"
    code_background_color = "#E5E5E5"
    code_block_color = "#FFF"
    code_block_background_color = "#272822"
    content_bg_color = "#FAF9F6"
    date_color = "#515151"
    link_color = "#005A94"
    list_color = "#5A5A5A"
    post_title_color = "#303030"
    table_border_color = "#E5E5E5"
    table_stripe_color = "#F9F9F9"
    text_color = "#222"

    # Hex colors for content in dark mode
    code_color_dark = "#FFF"
    code_background_color_dark = "#515151"
    code_block_color_dark = "#FFF"
    code_block_background_color_dark = "#272822"
    content_bg_color_dark = "#121212"
    date_color_dark = "#9A9A9A"
    link_color_dark = "#268BD2"
    list_color_dark = "#9D9D9D"
    post_title_color_dark = "#DBE2E9"
    table_border_color_dark = "#515151"
    table_stripe_color_dark = "#202020"
    text_color_dark = "#EEE"

    og_image = "/images/mahlstrom-profile-new.jpeg"

[taxonomies]
    series = 'series'
    tags = 'tags'